stages:
  - sync

sync_with_github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - git config --global user.name "VladShining"
    - git config --global user.email "vladshining@gmail.com"

    # Ajouter le dépôt GitHub comme remote
    - git remote add github https://github.com/VladShining/faker-ui.git

    # Assurez-vous que la branche actuelle est à jour
    - git fetch origin
    - git checkout main

  script:
    # Pousser les changements vers GitHub
    - git push github main

  only:
    - branches
